## Problem Statement 1:

## Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [25]:
import numpy as np

def gen_vander_matrix(iparray,n,increasing=False):
    
    if not increasing:
        op_matrix = np.array([x**(n-i-1) for x in iparray for i in range(n)])
        op_matrix = op_matrix.reshape(iparray.size,n)
    elif increasing:
        op_matrix = np.array([x**i for x in iparray for i in range(n)])
        op_matrix = op_matrix.reshape(iparray.size,n)
    return op_matrix

In [26]:
import numpy as np

x = np.array([3, 5, 7, 2, 8] )
no_of_output_columns = 4

op_matx_desc_order = gen_vander_matrix(x,4,False)
op_matx_asc_order  =  gen_vander_matrix(x,4,True)

print('Input array is :', x)
print("Number of columns in output matrix should be:",no_of_output_columns,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",op_matx_desc_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",op_matx_asc_order,"\n")

Input array is : [3 5 7 2 8]
Number of columns in output matrix should be: 4 

Vander matrix of the input array in decreasing order of powers:

 [[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [  8   4   2   1]
 [512  64   8   1]] 

Vander matrix of the input array in increasing order of powers:

 [[  1   3   9  27]
 [  1   5  25 125]
 [  1   7  49 343]
 [  1   2   4   8]
 [  1   8  64 512]] 



### Problem Statement 2:
'''
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
'''

In [27]:
def moving_average(input_array,k):
    n = len(input_array)
    l = []
    for i in range(0,n-k+1):
        val = np.sum(input_array[i:i+k])/k
        l.append(val)
    return np.array(l)
    

In [28]:
import numpy as np

x = np.array([3, 5, 7, 2, 8] )
x
print(moving_average(x,3))

[5.         4.66666667 5.66666667]


In [29]:
## Another Test
y = np.array([10,20,30,40,50,60,70,80,90,100])

print(moving_average(y,4))

[25. 35. 45. 55. 65. 75. 85.]


In [33]:
## Another Solution

import numpy as np
def moving_average(a, n=3) :
#     print('a:',a)
#     print('n:',n)
    ret = np.cumsum(a, dtype=float)
#     print(ret)
#     print(ret[n:])
#     print(ret[:-n])
    ret[n:] = ret[n:] - ret[:-n]
#     print('ret:',ret)
#     print(ret[n:])
    return ret[n - 1:] / n
a = [10,20,30,40,50,60,70,80,90,100]
print(moving_average(a, n=4))

[25. 35. 45. 55. 65. 75. 85.]
